= Eval Vim language

== Installation
=== minpac

.somewhere in .vimrc
[source,vim]
------------
call minpac#init()
" ...
" more plugins
" ...
call minpac#add('habamax/vim-evalvim')
------------

Then `:call minpac#update()` to install it.

=== vim-plug
.somewhere in .vimrc
[source,vim]
------------
call plug#begin('~/.vim/plugged')
" ...
" more plugins
" ...
Plug 'habamax/vim-evalvim'

call plug#end()
------------

Then `:PlugInstall` to install it.


== Usage

With default mappings turned on in your vimrc (`let g:evalvim_mappings = 1`):

[source,vim]
-------------
echo "hello world"
-------------

* `<leader>vv` to evaluate current line
* You should see `hello world` printed below


[source,vim]
-------------

fun! TestFun(p)
    return a:p
endfun
echomsg TestFun("Another Hello!")

-------------

* `<leader>vip` to evaluate current paragraph
* You should see `Another Hello` printed below

NOTE: You can also visually select text block and evaluate it with `<leader>v`.
Although you will not see the message printed -- you can find it in
`:messages`.


[source,vim]
-------------

set nu!
set cursorline!
set cursorcolumn!

-------------

* `<leader>vip` to evaluate current paragraph of settings
* line numbers, cursorline and cursorcolumns will be toggled


== Settings

To use default mappings add to your vimrc:

[source,vim]
-------------
let g:evalvim_mappings = 1
-------------


To use something else instead of `<leader>v` you remap ``<Plug>(EvalVim)``s, for example:

.vimrc
[source,vim]
-------------

xmap gy  <Plug>(EvalVim)
nmap gy  <Plug>(EvalVim)
omap gy  <Plug>(EvalVim)
nmap gyy <Plug>(EvalVimLine)

-------------

By default all output is captured to `*` and `"` registers so you can paste it
when needed.

To turn it off use:

[source,vim]
------------
let g:evalvim_capture_output = 0
------------
